name: Build
on: [push, pull_request]

jobs:
  build-win-x64:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Build
        run: |
          cd GptChat/GptChat.Desktop
          dotnet build --sc --runtime win-x64 -c Release

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: Releases/win-x64/setup.iss
          options: /O+

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GPT-chat-win-x64.exe
          path: Releases/win-x64/GPT-chat-setup.exe 
  
  build-linux-x64:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Build
        run: |
          cd GptChat/GptChat.Desktop
          dotnet build --sc --runtime linux-x64 -c Release

      - name: Prepare DEP package
        run: |
          cp -r GptChat/GptChat.Desktop/bin/Release/net8.0/linux-x64/. Releases/linux-x64/debpkg/opt/SergeiKrivko/GPT-chat-avalonia

      - name: Create DEB package
        uses: jiro4989/build-deb-action@v3
        with:
          package: gptchat-avalonia
          package_root: Releases/linux-x64/debpkg
          maintainer: SergeiKrivko
          version: 1.0.0
          arch: 'amd64'
          desc: 'GPT-chat-avalonia'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GPT-chat-linux-x64.deb
          path: gptchat-avalonia_1.0.0_amd64.deb
          
  build-macos-x64:
    name: Build for macOS
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Build
        run: |
          cd GptChat/GptChat.Desktop
          dotnet build --sc --runtime osx-x64 -c Release

      - name: Prepare package
        run: |
          cp -r GptChat/GptChat.Desktop/bin/Release/net8.0/osx-x64 Releases/mac-x64/GPT-chat-avalonia.app/Contents
          mv Releases/mac-x64/GPT-chat-avalonia.app/Contents/osx-x64 Releases/mac-x64/GPT-chat-avalonia.app/Contents/MacOS
          
          echo --------------------------------------- Releases/mac-x64/GPT-chat-avalonia.app/Contents
          ls Releases/mac-x64/GPT-chat-avalonia.app/Contents
          echo --------------------------------------- Releases/mac-x64/GPT-chat-avalonia.app/Contents/MacOS
          ls Releases/mac-x64/GPT-chat-avalonia.app/Contents/MacOS

      - name: Create installer
        uses: QQxiaoming/create-dmg-action@v0.0.2
        with:
          name: GPT-chat-avalonia
          srcdir: Releases/mac-x64/GPT-chat-avalonia.app

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GPT-chat-mac-x64.dmg
          path: GPT-chat-avalonia.dmg
  
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        run: |
          cd GptChat/GptChat.Android
          dotnet workload restore
          dotnet build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GPT-chat-avalonia.apk
          path: GptChat/GptChat.Android/bin/Debug/net8.0-android/com.CompanyName.GptChat-Signed.apk
